spring.application.name=portfolio
spring.profiles.active=dev
spring.profiles.group.dev=oauth

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security.web=trace
logging.level.org.zerock=debug

api.serviceKey=${env.PET_API_KEY}

jwt.secret=${env.JWT_SECRET}
jwt.expiration=86400

frontend.url=${env.FRONTEND_URL}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
